name: Test3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        run: |
          a=5
          name='{secrets.GH_TOKEN${a}}'
          echo name
          export GH_TOKEN = ${$name}
