name: Test5
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:        
      - name: Get Scorecard
        run: |
          wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
          tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
          mv scorecard-linux-amd64 scorecard
          
          
      - name: Score Repositroies
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE
          {
            for((i=0;i<100;i++));do
              echo $i
              repoName=https://github.com/laiyoufafa/applications_photos
              if [ `expr $i % 2` -wq 0];then
                export GH_TOKEN=${{ secrets.GH_TOKEN }}
              else
                export GH_TOKEN=${{ secrets.GH_TOKEN1 }}
              fi
              scorecard --repo $repoName --format json
              sleep 2.5s
              
            done  
          }&
          
          
          
             
          
          
          
          wait
          echo "finished"
