name: Test3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        run: |
          arr=(secrets.TOKEN1 secrets.TOKEN2 secrets.TOKEN3 secrets.TOKEN4 secrets.TOKEN5 secrets.TOKEN6 secrets.TOKEN7 secrets.TOKEN8 secrets.TOKEN9 secrets.TOKEN10 secrets.TOKEN11 secrets.TOKEN12 secrets.TOKEN13 secrets.TOKEN14 secrets.TOKEN15 secrets.TOKEN16 secrets.TOKEN17 secrets.TOKEN18 secrets.TOKEN19 secrets.TOKEN20 secrets.TOKEN21 secrets.TOKEN22 secrets.TOKEN23 secrets.TOKEN24)
          echo ${#arr[@]}
          echo $arr[3]
