name: Test3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Get Scorecard
       run: |
          wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
          tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
          mv scorecard-linux-amd64 scorecard
     - name: Get Repo List
       run: |
          arr=(${{secrets.GH_TOKEN1}} ${{secrets.GH_TOKEN2}} ${{secrets.GH_TOKEN3}} ${{secrets.GH_TOKEN4}} ${{secrets.GH_TOKEN5}} ${{secrets.GH_TOKEN6}} ${{secrets.GH_TOKEN7}} ${{secrets.GH_TOKEN8}} ${{secrets.GH_TOKEN9}} ${{secrets.GH_TOKEN10}} ${{secrets.GH_TOKEN11}} ${{secrets.GH_TOKEN12}} ${{secrets.GH_TOKEN13}} ${{secrets.GH_TOKEN14}} ${{secrets.GH_TOKEN15}} ${{secrets.GH_TOKEN16}} ${{secrets.GH_TOKEN17}} ${{secrets.GH_TOKEN18}} ${{secrets.GH_TOKEN19}} ${{secrets.GH_TOKEN20}} ${{secrets.GH_TOKEN21}} ${{secrets.GH_TOKEN22}} ${{secrets.GH_TOKEN23}} ${{secrets.GH_TOKEN24}})
          echo ${#arr[@]}
          export GH_TOKEN=$arr[3]
          export PATH=$PATH:$GITHUB_WORKSPACE
          scorecard --repo https://github.com/LikeFirstMeet/ScorecardForSlsaGenerator --format json
