name: Test4
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.SCORE_TS }}
          user: 'laiyoufafa'
          # (default)max_page: 10
          # (default)block_list:
          # (default)allow_empty: false
          # (default)allow_archived: true
          
      # /home/runner/work/ScoreCardActionForOpenHarmony/ScoreCardActionForOpenHarmony
      # - name: current PATH
      #  run: pwd
     
          
      - name: Get Scorecard
        run: |
          wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
          tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
          cp scorecard-linux-amd64 scorecard-first
          cp scorecard-linux-amd64 scorecard-second
          cp scorecard-linux-amd64 scorecard-third
          cp scorecard-linux-amd64 scorecard-fourth
          cp scorecard-linux-amd64 scorecard-fifth
          cp scorecard-linux-amd64 scorecard-sixth
          cp scorecard-linux-amd64 scorecard-seventh
          mv scorecard-linux-amd64 scorecard
          
          
      - name: Score Repositroies
        run: |
          # 将scorecard加入环境变量
          export PATH=$PATH:$GITHUB_WORKSPACE
          
          # 将仓库列表变成数组格式
          repos=${{steps.repo.outputs.repoList_ALL}}
          arr=(${repos//,/ })
          length=${#arr[@]}
          
          
          #1.创建有名管道
          [ -e ./fd1 ] || mkfifo ./fd1
          [ -e ./fd2 ] || mkfifo ./fd2
          [ -e ./fd3 ] || mkfifo ./fd3
          [ -e ./fd4 ] || mkfifo ./fd4
          [ -e ./fd5 ] || mkfifo ./fd5
          [ -e ./fd6 ] || mkfifo ./fd6
          [ -e ./fd7 ] || mkfifo ./fd7
          [ -e ./fd8 ] || mkfifo ./fd8
          exec 1<> ./fd1
          exec 2<> ./fd2
          exec 3<> ./fd3
          exec 4<> ./fd4
          exec 5<> ./fd5
          exec 6<> ./fd6
          exec 7<> ./fd7
          exec 8<> ./fd8
          rm -rf ./fd1
          rm -rf ./fd2
          rm -rf ./fd3
          rm -rf ./fd4
          rm -rf ./fd5
          rm -rf ./fd6
          rm -rf ./fd7
          rm -rf ./fd8
          #2.创建令牌
          echo >&1
          echo >&2
          echo >&3
          echo >&4
          echo >&5
          echo >&6
          echo >&7
          echo >&8
          echo >&1
          echo >&2
          echo >&3
          echo >&4
          echo >&5
          echo >&6
          echo >&7
          echo >&8
          #计数器
          count=0
          count_first=0
          count_second=0 
          count_third=0 
          count_four=0 
          count_fifth=0 
          count_sixth=0 
          count_seventh=0 
          count_eighth=0 
          
          {
            for((i=0;i<length;i++));do
              count_first=$(($count_first+1));
              count=$(($count+1));
              echo "count value :${count}"
              if [ $i -lt $length ];then
                    export GITHUB_AUTH_TOKEN=${{ secrets.GH_TOKEN1}}
                    repoName=https://github.com/laiyoufafa/${arr[$i]}
                    echo "time:${i}    repos_url:${repoName} "
                    str=""
                    str=$(scorecard --repo $repoName --format json) || true
                    echo $str
                    echo "name:first  ${repoName} finished"
              fi
            done
          }&
                    
          
          wait
          echo "finished"
         

