name: Test3
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo List
        run: |
          a=1
          GH_TOKEN1 = ${{secrets.GH_TOKEN}}
          echo $(GH_TOKEN$a)
