name: Test8
on:
#   schedule:
#   - cron: "0 3 * * 1-5"
  workflow_dispatch:
jobs:
  Thread-Finally:
      runs-on: ubuntu-latest
      steps:
        - name: Score Repositroies
          env: 
            GH_TOKEN: ${{secrets.GH_TOKEN}}
          run: |
            # 下载当前仓库
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGET_FILE=scorecards.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            touch $TARGET_FILE
            cat profile/a.txt >> $TARGET_FILE
            cat profile/b.txt >> $TARGET_FILE
            cat profile/c.txt >> $TARGET_FILE
            cat profile/d.txt >> $TARGET_FILE
            cat profile/e.txt >> $TARGET_FILE
            
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push 
