name: Test7
on:
#   schedule:
#   - cron: "0 3 * * 1-5"
  workflow_dispatch:

jobs:
  Init:
    runs-on: ubuntu-latest
    outputs:
      RepoList: ${{steps.repos.outputs.RepoList}}
    steps:
      - name: Get Repo List
        id: repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          my_token: ${{ secrets.SCORE_TS }}
          user: 'laiyoufafa'
          # (default)max_page: 10
          # (default)block_list:
          # (default)allow_empty: false
          # (default)allow_archived: true
      - name: RepoList
        id: repos
        run: |
          repos=${{steps.repo.outputs.repoList_ALL}}
          arr=(${repos//,/ })
          echo "RepoList=${arr[@]}" >> "$GITHUB_OUTPUT"    
  Thread-First:
    runs-on: ubuntu-latest
    needs: [Init]
    env: 
      RepoList: ${{needs.Init.outputs.RepoList}}
    steps:
      - name: Get Scorecard
        run: |
          wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
          tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
          mv scorecard-linux-amd64 scorecard
          
      - name: Score Repositroies
        id: first
        env: 
          GH_TOKEN: ${{secrets.GH_TOKEN1}}
        run: |
          export PATH=$PATH:$GITHUB_WORKSPACE
          FIRST_FILE=a.txt
          touch $FIRST_FILE
          arr=($RepoList)
          length=${#arr[@]}
          for((i=0;i<length;i=i+5));do
              count=$(($count+1));
              echo "count value :${count}"
              if [ $i -lt $length ];then
                    repoName=https://github.com/laiyoufafa/${arr[$i]}
                    echo "name:first time:${i}    repos_url:${repoName} "
                    str=""
                    str=$(scorecard --repo=$repoName --format=json) || true
                    echo $str >> $FIRST_FILE
                    echo "name:first  ${repoName} finished"
                    sleep 2s
              fi
          done
        
          export GH_TOKEN=${{secrets.GH_TOKEN}}
          gh repo clone $GITHUB_REPOSITORY /tmp/.github
          cd /tmp/.github
          TARGER_FILE=a.txt
          if [ ! -d "profile" ]; then
            mkdir profile
          fi
          if [ -f "$TARGET_FILE" ]; then
            rm $TARGET_FILE
          fi
          mv $GITHUB_WORKSPACE/$FIRST_FILE /tmp/.github/profile
          gh auth setup-git -h github.com
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update profile/scorecards.txt from CI"
          git push 

  Thread-Second:
      runs-on: ubuntu-latest
      needs: [Init]
      env: 
        RepoList: ${{needs.Init.outputs.RepoList}}
      steps:
        - name: Get Scorecard
          run: |
            wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
            tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
            mv scorecard-linux-amd64 scorecard

        - name: Score Repositroies
          id: second
          env: 
            GH_TOKEN: ${{secrets.USER2}}
          run: |
            export PATH=$PATH:$GITHUB_WORKSPACE
            SECOND_FILE=b.txt
            touch $SECOND_FILE
            arr=($RepoList)
            length=${#arr[@]}
            for((i=1;i<length;i=i+5));do
                count=$(($count+1));
                echo "count value :${count}"
                if [ $i -lt $length ];then
                      repoName=https://github.com/laiyoufafa/${arr[$i]}
                      echo "name:second time:${i}    repos_url:${repoName} "
                      str=""
                      str=$(scorecard --repo=$repoName --format=json) || true
                      echo $str >> $SECOND_FILE
                      echo "name:second  ${repoName} finished"
                      sleep 2s
                fi
            done
            export GH_TOKEN=${{secrets.GH_TOKEN}}
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGER_FILE=b.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            mv $GITHUB_WORKSPACE/$SECOND_FILE /tmp/.github/profile
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push

  Thread-Third:
      runs-on: ubuntu-latest
      needs: [Init]
      env: 
        RepoList: ${{needs.Init.outputs.RepoList}}
      steps:
        - name: Get Scorecard
          run: |
            wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
            tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
            mv scorecard-linux-amd64 scorecard

        - name: Score Repositroies
          id: third
          env: 
            GH_TOKEN: ${{secrets.USER3}}
          run: |
            export PATH=$PATH:$GITHUB_WORKSPACE
            THIRD_FILE=c.txt
            touch $THIRD_FILE
            arr=($RepoList)
            length=${#arr[@]}
            for((i=2;i<length;i=i+5));do
                count=$(($count+1));
                echo "count value :${count}"
                if [ $i -lt $length ];then
                      repoName=https://github.com/laiyoufafa/${arr[$i]}
                      echo "name:third time:${i}    repos_url:${repoName} "
                      str=""
                      str=$(scorecard --repo=$repoName --format=json) || true
                      echo $str >> $THIRD_FILE
                      echo "name:third  ${repoName} finished"
                      sleep 2s
                fi
             done
             export GH_TOKEN=${{secrets.GH_TOKEN}}
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGER_FILE=c.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            mv $GITHUB_WORKSPACE/$THIRD_FILE /tmp/.github/profile
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push

  Thread-Fourth:
      runs-on: ubuntu-latest
      needs: [Init]
      env: 
        RepoList: ${{needs.Init.outputs.RepoList}}
      steps:
        - name: Get Scorecard
          run: |
            wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
            tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
            mv scorecard-linux-amd64 scorecard

        - name: Score Repositroies
          id: fourth
          env: 
            GH_TOKEN: ${{secrets.USER4}}
          run: |
            export PATH=$PATH:$GITHUB_WORKSPACE
            FOURTH_FILE=d.txt
            touch $FOURTH_FILE
            arr=($RepoList)
            length=${#arr[@]}
            for((i=3;i<length;i=i+5));do
                count=$(($count+1));
                echo "count value :${count}"
                if [ $i -lt $length ];then
                      repoName=https://github.com/laiyoufafa/${arr[$i]}
                      echo "name:fourth time:${i}    repos_url:${repoName} "
                      str=""
                      str=$(scorecard --repo=$repoName --format=json) || true
                      echo $str >> $FOURTH_FILE
                      echo "name:fourth  ${repoName} finished"
                      sleep 2s
                fi
            done
            export GH_TOKEN=${{secrets.GH_TOKEN}}
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGER_FILE=d.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            mv $GITHUB_WORKSPACE/$FOURTH_FILE /tmp/.github/profile
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push

  Thread-Fifth:
      runs-on: ubuntu-latest
      needs: [Init]
      env: 
        RepoList: ${{needs.Init.outputs.RepoList}}
      steps:
        - name: Get Scorecard
          run: |
            wget https://github.com/ossf/scorecard/releases/download/v4.10.5/scorecard_4.10.5_linux_amd64.tar.gz
            tar -zxvf scorecard_4.10.5_linux_amd64.tar.gz
            mv scorecard-linux-amd64 scorecard

        - name: Score Repositroies
          id: fifth
          env: 
            GH_TOKEN: ${{secrets.SCORE_TS2}}
          run: |
            export PATH=$PATH:$GITHUB_WORKSPACE
            FIFTH_FILE=e.txt
            touch $FIFTH_FILE
            arr=($RepoList)
            length=${#arr[@]}
            for((i=4;i<length;i=i+5));do
                count=$(($count+1));
                echo "count value :${count}"
                if [ $i -lt $length ];then
                      repoName=https://github.com/laiyoufafa/${arr[$i]}
                      echo "name:fifth time:${i}    repos_url:${repoName} "
                      str=""
                      str=$(scorecard --repo=$repoName --format=json) || true
                      echo $str >> $FIFTH_FILE
                      echo "name:fifth  ${repoName} finished"
                      sleep 2s
                fi
            done
            export GH_TOKEN=${{secrets.GH_TOKEN}}
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGER_FILE=e.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            mv $GITHUB_WORKSPACE/$FIFTH_FILE /tmp/.github/profile
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push

  Thread-Finally:
      runs-on: ubuntu-latest
      needs: [Thread-First,Thread-Second,Thread-Third,Thread-Fourth,Thread-Fifth]
      steps:
        - name: Score Repositroies
          env: 
            GH_TOKEN: ${{secrets.GH_TOKEN}}
          run: |
            # 下载当前仓库
            gh repo clone $GITHUB_REPOSITORY /tmp/.github
            cd /tmp/.github
            TARGET_FILE=profile/scorecards.txt
            if [ ! -d "profile" ]; then
              mkdir profile
            fi
            if [ -f "$TARGET_FILE" ]; then
              rm $TARGET_FILE
            fi
            touch $TARGET_FILE
            cat profile/a.txt >> $TARGET_FILE
            cat profile/b.txt >> $TARGET_FILE
            cat profile/c.txt >> $TARGET_FILE
            cat profile/d.txt >> $TARGET_FILE
            cat profile/e.txt >> $TARGET_FILE
            
            gh auth setup-git -h github.com
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"
            git add .
            git commit -m "Update profile/scorecards.txt from CI"
            git push 

